import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/contexts/app/react-query-provider";
import { Suspense } from "react";
import LoadingScreen from "@/components/loading-screen";
import NpProgress from "@/components/NpProgress";
import AppProvider from "@/contexts/app/app-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NpProgress>
          <AppProvider>
            <ReactQueryProvider>
              <Suspense fallback={<LoadingScreen />}>
                {children}
                <Toaster position="top-center" />
              </Suspense>
            </ReactQueryProvider>
          </AppProvider>
        </NpProgress>
      </body>
    </html>
  );
}
